# Generated by Django 3.2.4 on 2021-07-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='published_date',
            new_name='published_year',
        ),
    ]
