# Generated by Django 3.2.4 on 2021-07-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_published_date_books_published_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='published_year',
            new_name='PublishDate',
        ),
        migrations.RemoveField(
            model_name='books',
            name='id',
        ),
        migrations.AlterField(
            model_name='books',
            name='ISBN',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
