# Generated by Django 3.2.4 on 2021-07-09 17:24

import books.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_auto_20210709_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowingPeriod', models.DateField(default=books.models.tenDays)),
                ('bookedBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
                ('bookedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('bookedBy', 'bookedBook')},
            },
        ),
    ]
