# Generated by Django 3.2.4 on 2021-07-09 17:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0005_bookings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='books',
            new_name='book',
        ),
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
    ]
