# Generated by Django 3.2.4 on 2021-07-11 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210709_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AddField(
            model_name='booking',
            name='borrowId',
            field=models.CharField(default=django.utils.timezone.now, max_length=5, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
