# Generated by Django 3.2.4 on 2021-07-11 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210711_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, default=5, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='borrowId',
            field=models.CharField(max_length=5),
        ),
    ]
