# Generated by Django 3.2.4 on 2021-07-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20210711_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='borrowId',
        ),
    ]
